### ISSUE TITLE
library doesn't allow \n in text

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-rich-text#10]
For example here is the very first demo:

<img width="629" alt="Screen Shot 2021-03-25 at 9 37 19 PM" src="https://user-images.githubusercontent.com/170009/112569511-48341500-8db2-11eb-8631-9c7e6faa5be6.png">

based on text:

```
`Let's make some
<ml>multiline</ml>
and <ms>multistyle</ms> text for
<pixi>Pixi.js!</pixi>`,
```

**Comment by rizen** [comment]
This one is preventing me from doing any testing or integrating into my app, so if you have time please have a look.

**Comment by mimshwright** [comment]
Something is up with the demo. This was all working fine AFAIK when I originally uploaded everything and sent you the link so I'll have to figure out what happened.

**Comment by mimshwright** [comment]
@rizen I'm still not sure how I missed this, but after testing, this commit seems to be the last good commit: 29dbc806ef424f640275eebbc145d85f88bd35cf
If you need to use something for testing, I'd check that out and start there while I figure it out.
