### ISSUE TITLE
right justify has some oddities

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-rich-text#18]
Given this text:

```
there is enough text here to make  multiple lines once you factor in word wrap.\n\nAnd here is a whole new line all together!
```
With font size of 50 and a word wrap of 200, and align set to justify I get this:

<img width="256" alt="Screen Shot 2021-04-02 at 7 21 58 PM" src="https://user-images.githubusercontent.com/170009/113462922-dc246300-93e8-11eb-91cd-a1bad7f1fd74.png">

There are several things I can see wrong.

* here to make - "make" isn't at the right edge
* the second sentence "And" doesn't start at the left edge
* the end of the first line of the second sentence "a" isn't at the right edge

**Comment by mimshwright** [comment]
This is basically the same issue (or at least the same fix) as #5. I'mn going to mark it as a duplicate.
