### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by mimshwright** [mimshwright/pixi-rich-text#22]
When done need to publish.

**Comment by mimshwright** [comment]
Turns out there are some naming conflicts on npm. 

pixi-rich-text is taken.
pixi-muiltistyle-text is taken.

Some ideas:

- TaggedText
- MarkupText
- HTMLText / XMLText / HTMLStyledText
- TypesetText / LettersetText
- namespace using @mimshwright  or @plainblack as in "@plainblack/pixi-multistyle-text"

Also could be possible to merge these changes back into @tleunen's pixi-multistyle-text as a new major version.

**Comment by tleunen** [comment]
@mimshwright It's up to you. But I don't have any objections with having a breaking change in pixi-multistyle-text if it's all in favor to improve the library and there's a way to migrate from one version to another ;) Some features could eventually be lost, but ideally, no major ones.

**Comment by mimshwright** [comment]
@tleunen I ended up re-creating the component in almost every way. To be honest, I would assume your version would probably be more performant - yours does layout using canvas drawing and mine actually creates several PIXI.Text objects within a PIXI.Sprite. There are features we don't implement and don't really want to such as BBCode. Since they're so different, I think maybe they should just remain separate. 

To me, TaggedText is the simplest and most descriptive name (that isn't taken) so I'll go with that. 

BTW, I just today learned of [yet another one](https://github.com/pixijs/html-text). I don't know if this works well for what we wanted (sounds like maybe it uses the browser somehow to render the text?) but good to know about.

**Comment by mimshwright** [comment]
It's published as pixi-tagged-text v2.0.0. If you want to replace MultiStyleText then I think first take a look and see if it is something you want to do.

**Comment by tleunen** [comment]
`pixijs/html-text` is very interesting, especially if it supports everything. But if I recall, there are things that can be done in canvas that are hard to do with basic html. Anyway, for most usage, I'd bet it would be all good.

[It renders in a svg](https://github.com/pixijs/html-text/blob/472ffe3ba91c370238b2139d82d5921fd0b21d43/src/index.js#L140-L146), and then [copy the result into the canvas](https://github.com/pixijs/html-text/blob/472ffe3ba91c370238b2139d82d5921fd0b21d43/src/index.js#L168-L180), that's a good idea :) Relying one the browser for the complicated parts.
