### ISSUE TITLE
v2: asymmetric text fill

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-rich-text#30]
This is also speculative depending upon the effort involved. 

What would it take to give a graphic (circle, rectangle, polygon) with size and position, and then use that as a mask for fitting text to the text box?

**Comment by mimshwright** [comment]
Rectangle is already possible 😉 

as for the rest, I would imagine it's difficult. Or to put it another way, I could imagine a way of doing it with circles using some clever geometry, but i don't even have a clue how you would do it with an arbitrary shape.

**Comment by rizen** [comment]
Alright, that's all I needed to know. Thanks!
