### ISSUE TITLE
Nesting a self-closing tag inside of another tag throws an error.

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-rich-text#6]
```
<tag><icon /></tag> 
```

errors saying that it found ```</tag>``` without a matching start tag.

Real world example:
```
<outline><thinking /></outline>
```
Browser error:
Error: Unexpected tag nesting. Found a closing tag "</outline>" that doesn't match the previously open tag "<thinking>"

**Comment by mimshwright** [comment]
Repro:
```typescript
new RichText(
  `<b>Nested <i /> self-closing tag</b>`,
  {
    b: { fontWeight: "bold",},
    i: { fontStyle: "italic" }
  }
);
```

Expected:
**Nested self-closing tag** (empty i tag is ignored)

Actual:
Browser error:
`Error: Unexpected tag nesting. Found a closing tag "<b>" that doesn't match the previously open tag "<i>"`

**Comment by mimshwright** [comment]
accidentally referenced the wrong bug in that commit
