### ISSUE TITLE
Full and right justify with 2 different font sizes gets different right hand results.

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-rich-text#7]
First line 36px. Second line 24px. Third (and fourth) are 40px. You can see that the different sizes have a different "right" side.

<img width="536" alt="Screen Shot 2021-03-25 at 5 32 33 PM" src="https://user-images.githubusercontent.com/170009/112552116-43f70000-8d90-11eb-9419-5e243670a4bd.png">

**Comment by mimshwright** [comment]
good catchz

**Comment by mimshwright** [comment]
@rizen Can you paste in your example code from this one?

**Comment by rizen** [comment]
```

let text = `
<h2>Inline Images!</h2> 
You can put icons directly into your text <bear /> <outline><thinking></thinking></outline>. 
<big><shadow>Almost</shadow> <red>before</red> <b>we</b> <i>knew</i> <outline>it</outline>, we had left the <b><i><outline><red><shadow>ground</shadow></red></outline></i></b>.</big>
`;

const style = {
  default: {
    fontFamily: "Arial",
    fontSize: "24px",
    fill: "#000000",
    imgDisplay : 'icon',
    align: 'right',
  },
  
  h2: {
    fontSize: 36,
    fill: "#44CC99",
    fontFamily: 'Inconsolata',
  },
  bear : {
    fontSize: '36px',
  },

  big : {
    fontFamily: "New Tegomin",
    fontSize: 40,
  },
  shadow: { dropShadow: true, dropShadowColor: "#888888" },
  outline: { stroke: "blue", strokeThickness: 2 },
  b: { fontWeight: 900 },
  red: { fill: "red" },
  i: { fontStyle: "italic" },
          
}

const options = {imgMap: { 
  bear :  PIXI.Sprite.from("./img/bear.png"),
  thinking :  PIXI.Sprite.from("./icon.png"),
},
debug: true,
};

const imgText = new RichText(text, style, options);

```

**Comment by mimshwright** [comment]
I looked into this and it appears to be something to do with the fix for dangling spaces and punctuation on right aligned text from e386f3ed97948beb63688e6f1d34a1a6a2260413. The offending code is probably at line 376 of layout.ts.

**Comment by mimshwright** [comment]
I saw that the alignment isn't perfect on Justify (the final period sticks out a couple of pixels) but I think the fix for https://github.com/mimshwright/pixi-rich-text/issues/5 will help improve the overall layout.
