### ISSUE TITLE
Multiple carriage returns in a row are ignored, but should not be

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-rich-text#8]
Given:

```
const text = `word1


word2`
```

The result is
<img width="121" alt="Screen Shot 2021-03-25 at 5 35 17 PM" src="https://user-images.githubusercontent.com/170009/112552308-93d5c700-8d90-11eb-8b62-942d940bfdba.png">

**Comment by mimshwright** [comment]
fixed in ca8c501c90bf64bf2e926086d957d817d1c206b0 but accidentally referenced the wrong issue in the commit message.
